apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
  minReplicas: 3
  maxReplicas: 3  # Adjust this as needed
  targetCPUUtilizationPercentage: 5 # Adjust this to a low value for quick testing
