apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: employees
    component: frontend
spec:
  type: LoadBalancer  # Change the service type to LoadBalancer
  ports:
  - port: 81
    targetPort: 81
  selector:
    app: employees
